"""Initialmigration

Revision ID: 78337ecd6805
Revises: 
Create Date: 2025-11-13 21:39:11.718752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78337ecd6805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('ConsumerID', sa.Integer(), nullable=False),
    sa.Column('CompanyName', sa.String(length=255), nullable=False),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Type', sa.Enum('RESTAURANT', 'HOTEL', 'OTHER', name='consumertype'), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ConsumerID')
    )
    op.create_index(op.f('ix_consumers_ConsumerID'), 'consumers', ['ConsumerID'], unique=False)
    op.create_table('suppliers',
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('CompanyName', sa.String(length=255), nullable=False),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('VerificationStatus', sa.Boolean(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('SupplierID')
    )
    op.create_index(op.f('ix_suppliers_SupplierID'), 'suppliers', ['SupplierID'], unique=False)
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Role', sa.Enum('ADMIN', 'REGULAR', name='userrole'), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_UserID'), 'users', ['UserID'], unique=False)
    op.create_table('consumer_staff',
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ConsumerID', sa.Integer(), nullable=False),
    sa.Column('Role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='consumerstaffrole'), nullable=False),
    sa.Column('JoinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ConsumerID'], ['consumers.ConsumerID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('StaffID')
    )
    op.create_index(op.f('ix_consumer_staff_StaffID'), 'consumer_staff', ['StaffID'], unique=False)
    op.create_table('links',
    sa.Column('LinkID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('ConsumerID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REMOVED', 'BLOCKED', name='linkstatus'), nullable=True),
    sa.Column('RequestedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ApprovedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ConsumerID'], ['consumers.ConsumerID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('LinkID')
    )
    op.create_index(op.f('ix_links_LinkID'), 'links', ['LinkID'], unique=False)
    op.create_table('products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Unit', sa.String(length=50), nullable=True),
    sa.Column('Stock', sa.Integer(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('MinimumOrderQuantity', sa.Integer(), nullable=True),
    sa.Column('ImageURL', sa.String(length=500), nullable=True),
    sa.Column('DeliveryAvailable', sa.Boolean(), nullable=True),
    sa.Column('PickupAvailable', sa.Boolean(), nullable=True),
    sa.Column('LeadTime', sa.String(length=100), nullable=True),
    sa.Column('DeliveryZones', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['SupplierID'], ['suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_index(op.f('ix_products_ProductID'), 'products', ['ProductID'], unique=False)
    op.create_table('supplier_staff',
    sa.Column('StaffID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('Role', sa.Enum('OWNER', 'MANAGER', 'SALES', name='supplierstaffrole'), nullable=False),
    sa.Column('JoinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['SupplierID'], ['suppliers.SupplierID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('StaffID')
    )
    op.create_index(op.f('ix_supplier_staff_StaffID'), 'supplier_staff', ['StaffID'], unique=False)
    op.create_table('chats',
    sa.Column('ChatID', sa.Integer(), nullable=False),
    sa.Column('LinkID', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['LinkID'], ['links.LinkID'], ),
    sa.PrimaryKeyConstraint('ChatID'),
    sa.UniqueConstraint('LinkID')
    )
    op.create_index(op.f('ix_chats_ChatID'), 'chats', ['ChatID'], unique=False)
    op.create_table('orders',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('ConsumerID', sa.Integer(), nullable=False),
    sa.Column('ConsumerStaffID', sa.Integer(), nullable=False),
    sa.Column('OrderDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('DeliveryDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('RejectionReason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ConsumerID'], ['consumers.ConsumerID'], ),
    sa.ForeignKeyConstraint(['ConsumerStaffID'], ['consumer_staff.StaffID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_index(op.f('ix_orders_OrderID'), 'orders', ['OrderID'], unique=False)
    op.create_table('complaints',
    sa.Column('ComplaintID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('ConsumerStaffID', sa.Integer(), nullable=False),
    sa.Column('SupplierStaffID', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('Status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='complaintstatus'), nullable=True),
    sa.Column('Priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='complaintpriority'), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ResolvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ConsumerStaffID'], ['consumer_staff.StaffID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['orders.OrderID'], ),
    sa.ForeignKeyConstraint(['SupplierStaffID'], ['supplier_staff.StaffID'], ),
    sa.PrimaryKeyConstraint('ComplaintID')
    )
    op.create_index(op.f('ix_complaints_ComplaintID'), 'complaints', ['ComplaintID'], unique=False)
    op.create_table('messages',
    sa.Column('MessageID', sa.Integer(), nullable=False),
    sa.Column('ChatID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('SentAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('IsRead', sa.Boolean(), nullable=True),
    sa.Column('MessageType', sa.String(length=50), nullable=True),
    sa.Column('FileURL', sa.String(length=500), nullable=True),
    sa.Column('ProductLinkID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ChatID'], ['chats.ChatID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('MessageID')
    )
    op.create_index(op.f('ix_messages_MessageID'), 'messages', ['MessageID'], unique=False)
    op.create_table('order_items',
    sa.Column('OrderItemID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['orders.OrderID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['products.ProductID'], ),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    op.create_index(op.f('ix_order_items_OrderItemID'), 'order_items', ['OrderItemID'], unique=False)
    op.create_table('complaint_logs',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('ComplaintID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Action', sa.String(length=255), nullable=False),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ComplaintID'], ['complaints.ComplaintID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    op.create_index(op.f('ix_complaint_logs_LogID'), 'complaint_logs', ['LogID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_logs_LogID'), table_name='complaint_logs')
    op.drop_table('complaint_logs')
    op.drop_index(op.f('ix_order_items_OrderItemID'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_messages_MessageID'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_complaints_ComplaintID'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_orders_OrderID'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_chats_ChatID'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_supplier_staff_StaffID'), table_name='supplier_staff')
    op.drop_table('supplier_staff')
    op.drop_index(op.f('ix_products_ProductID'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_links_LinkID'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_consumer_staff_StaffID'), table_name='consumer_staff')
    op.drop_table('consumer_staff')
    op.drop_index(op.f('ix_users_UserID'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_SupplierID'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_consumers_ConsumerID'), table_name='consumers')
    op.drop_table('consumers')
    # ### end Alembic commands ###

